### ISSUE TITLE
Feature Request: Epic Loot Compatibility

### ISSUE THREAD

**Issue by XzeroAir** [Ivaylo-Lafchiev/ValheimRecycle#1]
Using version 1.1.1, I Noticed when Recycling an item that was Enchanted by the Epic Loot Mod, It lost all enchants when downgrading.

Would it be possible to have it not lose the enchantments when recycling, and have a config to toggle it?

**Comment by Ivaylo-Lafchiev** [comment]
My best guess is that it's possible but would require constant updating to keep it compatible. I'll take a look when I get a chance.

**Comment by XzeroAir** [comment]
Ah, so probably wont be worth the effort to implement xD
well, if you can work something out, that'd be cool, and appreciated, if not, then oh well, Figured I'd Ask.

**Comment by Ivaylo-Lafchiev** [comment]
Right now, when you recycle an item, instead of changing the quality of your existing item, it actually removes it and gives you a new item with quality - 1. This is basically an exact copy of how upgrade works, except decreasing quality instead of increasing it.

A better solution might be to just modify the quality of the existing item. If that works then hopefully any other data like enchantments on the item can be preserved.

**Comment by Ivaylo-Lafchiev** [comment]
The issue of enchants being lost should be solved now in 1.2.1.
